- README.md
- README_ESC.md
- README_TC.md
- README_TFC.md
- app/calculators/CCCalculator.scala
- app/calculators/ESCCalculator.scala
- app/calculators/TCCalculator.scala
- app/calculators/TFCCalculator.scala
- app/config/CcGlobal.scala
- app/controllers/esc/ESCCalculatorController.scala
- app/controllers/tc/TaxCreditCalculatorController.scala
- app/controllers/tfc/TFCCalculatorController.scala
- app/service/AuditService.scala
- app/utils/CCConfig.scala
- app/utils/ESCSchemeConfig.scala
- app/utils/JSONFactory.scala
- app/utils/Periods.scala
- app/utils/TCSchemeConfig.scala
- app/utils/TFCSchemeConfig.scala
- conf/application-json-logger.xml
- conf/application-logger.xml
- project/MicroService.scala
- test/utils/CCJsonLogger.scala
- test/utils/JSONFactorySpec.scala
> Updated headings

- project/MicroService.scala
- project/MicroServiceBuild.scala
- project/plugins.sbt
@shridhaarchippaa @roma-silimcano
> Ccalc 2245

- app/calculators/CCCalculator.scala
- app/calculators/ESCCalculator.scala
- app/calculators/TCCalculator.scala
- app/calculators/TFCCalculator.scala
- app/config/CcGlobal.scala
- app/controllers/esc/ESCCalculatorController.scala
- app/controllers/tc/TaxCreditCalculatorController.scala
- app/controllers/tfc/TFCCalculatorController.scala
- app/models/input/APIModels.scala
- app/models/input/esc/ESCEligibility.scala
- app/models/input/tc/TCEligibility.scala
- app/models/input/tfc/TFCEligibility.scala
- app/models/output/tc/TCCalculation.scala
- app/service/AuditService.scala
- app/utils/CCConfig.scala
- app/utils/ESCSchemeConfig.scala
- app/utils/Periods.scala
- app/utils/TCSchemeConfig.scala
- app/utils/TFCSchemeConfig.scala
- scalastyle-config.xml
> Ccalc 2393

- conf/config-tc.conf
- test/controllers/tc/TaxCreditCalculatorControllerSpec.scala
- test/resources/json/tc/input/2018/scenario_1.json
- test/resources/json/tc/input/2018/scenario_2.json
- test/resources/json/tc/input/2018/scenario_3.json
- test/resources/json/tc/input/2018/scenario_4.json
- test/resources/json/tc/input/2018/scenario_5.json
- test/scenarios/TCScenarioSpec.scala
- test/utils/TCSchemeConfigSpec.scala
> Ccalc 2539

- app/calculators/TCCalculator.scala
- app/controllers/tc/TaxCreditCalculatorController.scala
- test/calculators/TCCalculatorSpec.scala
> Check childcare eligibility before giving the childcare element

- app/calculators/TCCalculator.scala
- test/calculators/TCCalculatorSpec.scala
> Ccalc 2600

- app/calculators/ESCCalculator.scala
- app/controllers/esc/ESCCalculatorController.scala
- app/controllers/tc/TaxCreditCalculatorController.scala
- app/controllers/tfc/TFCCalculatorController.scala
- conf/app.routes
- project/MicroServiceBuild.scala
- project/plugins.sbt
- test/controllers/esc/ESCCalculatorControllerSpec.scala
- test/controllers/tc/TaxCreditCalculatorControllerSpec.scala
- test/controllers/tfc/TFCCalculatorControllerSpec.scala
> Ccalc 2725

- scalastyle-config.xml
> Fix scalastyle warnings

- app/calculators/TCCalculator.scala
- app/config/CcGlobal.scala
- conf/application.conf
- project/MicroServiceBuild.scala
> Ccalc 2682

- app/calculators/CCCalculator.scala
- app/calculators/TFCCalculator.scala
- app/controllers/tfc/TFCCalculatorController.scala
- app/models/input/tfc/TFCEligibility.scala
- app/models/output/tfc/TFCCalculation.scala
- app/utils/TFCSchemeConfig.scala
- test/calculators/TFCCalculatorSpec.scala
- test/models/input/TFCEligibilitySpec.scala
- test/resources/json/tfc/output/scenario_27.json
> Added period eligibility logic for calculating both parent and child

- README_ESC.md
- README_TC.md
@shridhaarchippaa - please merge
> CCALC-2884 Updated readme for tcc and esc scheme objects

- app/calculators/TCCalculator.scala
- app/controllers/tc/TaxCreditCalculatorController.scala
- app/models/input/tc/TCCalculatorInput.scala
- test/calculators/TCCalculatorSpec.scala
- test/controllers/tc/TaxCreditCalculatorControllerSpec.scala
- test/models/input/TCCalculatorInputSpec.scala
- test/scenarios/TCScenarioSpec.scala
- test/utils/JSONFactorySpec.scala
> CCALC-2934 Updated input output models as per cc-frontend

- app/utils/ESCSchemeConfig.scala
- test/utils/ESCSchemeConfigSpec.scala
@shridhaarchippaa @milena-valchanova
> CCALC Coverage improved

- test/utils/JSONFactorySpec.scala
> CCALC - Coverage improved

- app/calculators/ESCCalculator.scala
- test/calculators/ESCCalculatorSpec.scala
@shridhaarchippaa @kapil-sanghvi @zatevad
> Give most of childcare cost to highest earner

- app/utils/ESCSchemeConfig.scala
- conf/config-esc.conf
- test/utils/ESCSchemeConfigSpec.scala
- test/utils/FakeCCCalculatorApplication.scala
@shridhaarchippaa @milena-valchanova @kapil-sanghvi @zatevad Please review and merge if happy. Thanks
> Removed feature switch for scotish rate of tax

- app/calculators/ESCCalculator.scala
- app/controllers/esc/ESCCalculatorController.scala
- app/utils/ESCSchemeConfig.scala
- conf/config-esc.conf
- test/calculators/ESCCalculatorSpec.scala
- test/utils/ESCSchemeConfigSpec.scala
@shridhaarchippaa @kapil-sanghvi @zatevad
> Ccalc 3037

- app/models/input/tc/TCCalculatorInput.scala
- test/calculators/TCCalculatorSpec.scala
- test/resources/json/tc/input/valid_json.json
> CCALC-3223-FIX updated calculator input for TC scheme

- project/MicroServiceBuild.scala
> Library upgrade

- repository.yaml
Leak Detection Service exemption to stop false-positive issue detected in test code
> Adding LDS exemption

- conf/application.conf
> DL-4688 - removing httpOnly config

- .gitignore
- app/service/AuditService.scala
- conf/application.conf
- project/AppDependencies.scala
- test/service/AuditServiceTest.scala
> DL-5434 Bootstrap 2.7 upgraded to 4.2.0

- build.sbt
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
- test/service/AuditEventsTest.scala
- test/service/AuditServiceTest.scala
> DL-5468 - Bootstrap upgrade to 5.x.x

- app/calculators/ESCCalculator.scala
- app/utils/ESCSchemeConfig.scala
- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
- test/calculators/CCCalculatorHelperSpec.scala
- test/calculators/ESCCalculatorSpec.scala
- test/calculators/TCCalculatorSpec.scala
- test/calculators/TFCCalculatorSpec.scala
- test/controllers/CalculatorControllerSpec.scala
- test/controllers/esc/ESCCalculatorControllerSpec.scala
- test/controllers/tc/TaxCreditCalculatorControllerSpec.scala
- test/controllers/tfc/TFCCalculatorControllerSpec.scala
- test/service/AuditEventsTest.scala
- test/service/AuditServiceTest.scala
- test/utils/ESCSchemeConfigSpec.scala
- test/utils/JSONFactorySpec.scala
- test/utils/PeriodsSpec.scala
- test/utils/TCSchemeConfigSpec.scala
- test/utils/TFCSchemeConfigSpec.scala
**Bug fix / New feature** (delete as appropriate)
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).
> DL-5750 Play 2.8 upgrade

- build.sbt
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
- test/service/AuditEventsTest.scala
- test/service/AuditServiceTest.scala
Bootstrap-play upgrade to version 5.24.0 and other general dependency upgrade completed
> DL-8089 bootstrap upgrade to 5.24.0 and general dependency upgrade

- conf/application.conf
**Bug fix / New feature** (delete as appropriate)
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).
> DL-11195 removing unused config keys

- build.sbt
**Bug fix / New feature** (delete as appropriate)
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).
> DL-12419 disabled Junit xml report

- project/AppDependencies.scala
- project/plugins.sbt
> DL-15065:Updating the service with latest version of dependencies.

- project/AppDependencies.scala
- project/plugins.sbt
DL-15286:Rectifying bobby violation
> DL-15286:Rectifying bobby violation
